! Definitions file for HTAP-PRM RUN 

! Run-Mode: Parameters that affect how htap-prm is configured. 
RunParameters_START
  run-mode                           = sample{n:15; seed:436} 
  archetype-dir                      = C:/HTAP/Archetypes
RunParameters_END 

! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future. 
RunScope_START

  archetypes                        = BC-Step-MediumSFD.h2k
  locations                         = NA 
  rulesets                          = as-found 
  
  
RunScope_END

! Parameters controlling the design of the building 
Upgrades_START

  ! Opt-FuelCost         = rates2016
  ! Opt-DBFiles          = NA
  ! Opt-ResultHouseCode  = NA
  !
  ! Opt-Specifications   = NA
  !
  Opt-Baseloads        = *   
  Opt-Temperatures     = *
  ! 
  Opt-ACH              = *
  ! 
  Opt-CasementWindows  = *

  Opt-Ceilings         = *

    
Upgrades_END