! Definitions file for HTAP-PRM RUN

! Run-Mode: Parameters that affect how htap-prm is configured.
RunParameters_START
  run-mode                           = parametric
  archetype-dir                      = C:/HTAP/Archetypes
  unit-costs-db                      = C:/HTAP/HTAPUnitCosts.json
  options-file                       = C:/HTAP/HTAP-options.json
  !rulesets-file                      = C:/HTAP/HTAP-rulesets.json
RunParameters_END


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future.
RunScope_START

  archetypes                        = NRCan-arch4_2100sf_2storey_fullBsmt.h2k
  locations                         = VANCOUVER 
  rulesets                          = NBC9_36[fuel>gas;vent>HRV]y


RunScope_END

! Parameters controlling the design of the building
Upgrades_START

   !upgrade-package-list     = NA, test-a

   Opt-FuelCost         = rates2016

   Opt-ResultHouseCode  = General

   Opt-Specifications   = NA

   Opt-Baseloads        = NA
   Opt-Temperatures     = NA

   Opt-ACH              = NA 

   Opt-CasementWindows  = NA 

   Opt-GenericWall_1Layer_definitions = NA ! , NC_R-18(eff)_2x6-24inOC_R22-batt_poly_vb,NC_R-21(eff)_2x6-16inOC_R19-batt+1inXPS_poly_vb, NC_R-20(eff)_2x6-24inOC_2lb.ClosedCellSprayFoam_poly_vb, NC_R-24(eff)_2x6-24inOC_R19-batt+1.5inXPS_poly_vb, NC_R-28(eff)_2x6-24inOC_R22-batt+2inXPS_poly_vb

   Opt-DHWSystem        = NA
   Opt-HVACSystem       = NA !, CCASHP, GSHP
   Opt-DWHRSystem       = NA !, DWHR-eff-30, DWHR-eff-55


Upgrades_END
