! Definitions file for HTAP-PRM RUN

! Run-Mode: Parameters that affect how htap-prm is configured.
RunParameters_START
  run-mode                           = parametric
  archetype-dir                      = C:/HTAP/Archetypes
  unit-costs-db                      = C:/HTAP/HTAPUnitCosts.json
RunParameters_END


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future.
RunScope_START

  archetypes                        = BC-Step-MediumSFD.h2k , BC-Step-SmallSFD.h2k
  locations                         = CALGARY , VANCOUVER, EDMONTON
  rulesets                          = as-found ! NBC9_36_HRV  !, R2000_NZE_Pilot_Env


RunScope_END

! Parameters controlling the design of the building
Upgrades_START

   Opt-FuelCost         = rates2016

   Opt-ResultHouseCode  = NA

   Opt-Specifications   = NA

   Opt-Baseloads        = NA
   Opt-Temperatures     = NA

   Opt-ACH              = NA !, New-Const-air_seal_to_4-6_ach, New-Const-air_seal_to_3.50_ach, New-Const-air_seal_to_2.50_ach, New-Const-air_seal_to_1.50_ach, New-Const-air_seal_to_1.00_ach

   Opt-CasementWindows  = NA !, NC-2g-HG-u1.82    , NC-2g-HG-u1.65 , NC-2g-LG-u1.65, NC-3g-LG-u1.14, NC-3g-HG-u1.08, NC-3g-HG-u1.36
   Opt-Skylights        = NA
   Opt-DoorWindows      = NA
   Opt-Doors            = NA

   Opt-MainWall         = NA
   Opt-GenericWall_1Layer_definitions = NA !
   Opt-FloorHeader      = NA

   Opt-H2KFoundation    = Rigid+BattR30-R24BSlab
   Opt-H2KFoundationSlabCrawl = NA

   Opt-FoundationWallExtIns :     uninsulated ! xps2inEffR10
   Opt-FoundationWallIntIns :     uninsulated ! WoodFrameEffR15
   Opt-FoundationSlabBelowGrade : uninsulated !  xps4inEffR20
   Opt-FoundationSlabOnGrade :    uninsulated !


   Opt-ExposedFloor     = NA
   Opt-ExposedFloor      = NA

   Opt-FloorAboveCrawl  = NA

   Opt-Ceilings         = NA  !, CeilR40    , CeilR50, CeilR60, CeilR70,CeilR80,CeilR90, CeilR100
   Opt-AtticCeilings    = NA
   Opt-CathCeilings     = NA
   Opt-FlatCeilings     = NA

   Opt-HRVonly          = NA
   Opt-HRVspec          = NA
   Opt-DHWSystem        = NA
   Opt-HVACSystem       = NA
   Opt-DWHRSystem       = NA !, DWHR-eff-30, DWHR-eff-55
   Opt-H2K-PV           = NA


Upgrades_END
