
# HARD-Coded text to be inserted in h2k magic files. Space sensitive; saved
# stored separately to reduce the likelyhood of them getting messed up. 

H2K_ini_out=
"[HOT2000]
LANGUAGE=E
ECONOMIC_FILE=%PATH%\\H2K\\StdLibs\\econLib.eda
WEATHER_FILE=%PATH%\\H2K\\Dat\\Wth110.dir
FUELCOST_FILE=%PATH%\\H2K\\StdLibs\\fuelLib.flc
CODELIB_FILE=%PATH%\\H2K\\StdLibs\\codeLib.cod
HSEBLD_FILE=%PATH%\\H2K\\Dat\\XPstd.slb
UPDATES_URI=http://198.103.48.154/hot2000/LatestVersions.xml
CHECK_FOR_UPDATES=N
UNITS=M
"

H2K_rout_str =
"<Choose diagnostics>
All,
<End>
x 'Boot', ! 1 = Startup
x 'Calculations', ! 2 = Anncal, HseChk, FndChk...
x 'DHW', ! 3 = All DHW routines
x 'Space Heat', ! 4 = Space heating system models
x 'Space Heat Ini', ! 5 = Space heating initialization
x 'IMS', ! 6 = IMS model
x 'AIM2', ! 7 = AIM2 model
x 'HRV', ! 8 = HRV model + Fans No HR
x 'BHB', ! 9 = Basement Heat balance
x 'Rooms', ! 10 = Room by room calcs
x 'C/S', ! 11 = Crawl Space'
x 'Slab',! 12 = Slab on Grade
x 'Cooling', ! 13 = Cooling
x 'P9', !   14 = P9 Combo
x 'Windows', ! 15 = Window diagnostics (need this even when All specified
x 'Wizard', ! 16 = HOT2000 Wizard

(This version auto-generated by substitute-h2k.rb)

Put this file in the HOT2000 program directory to turn on diagnostics.
When HOT2000 is started up, a message will appear to state that the
diagnostics will be written to a file named Routstr.Txt.  Other message
boxes will appear on the screen as calculations, ETC occur.  Click OK to
proceed, but note the last message box to appear before the problem
occurs.
JB> Other setting under <Choose diagnostics> is \"Calculations\"
The contents of the diagnostics file were not intended to be of much
use to the general user, but may be useful to the developers in
determining problems with calculations ETC.
This tool should only be used once, I.E. for a single run that causes
the problem to be analysed.
- put the file in the program directory (where HOT2000.exe is located)
- run HOT2000, open the file in question, do the run, quit the program
- e-mail the file Routstr.txt (Winzip/compress it to reduce space) to
  HOT2000 support.
- rename Routstr.h2k to 0Routstr.h2k to suppress the diagnostics
  Brian Bradley
  bbradley@nrcan.gc.ca
  204-984-4920"
