! Definitions file for HTAP-PRM RUN 

! Run-Mode: Parameters that affect how htap-prm is configured. 
RunParameters_START
  run-mode                           = mesh 
  archetype-dir                      = C:\HTAP\testing\GeneralVsSOC\h2kfiles
RunParameters_END 


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if anoptimization mode is added in the future. 

RunScope_START

  archetypes                        = NRCan-A11_1500sf_2storey_rowMid_fullBsmt-GEN.h2k, NRCan-A11_1500sf_2storey_rowMid_fullBsmt-GENpVR.h2k, NRCan-A11_1500sf_2storey_rowMid_fullBsmt-SOC.h2k
  locations                         = Ottawa  
  rulesets                          = as-found
  
RunScope_END

! Parameters controlling the design of the building 
Upgrades_START

    Opt-FuelCost                       = rates2016      ! Maybe this belongs in scope?
    Opt-ACH                            = NA, ACH_1_0, ACH_2_0, ACH_3,ACH_4, ACH_5,ACH_6, ACH_7
    Opt-MainWall                       = GenericWall_1Layer
    Opt-ResultHouseCode                = SOC
    Opt-GenericWall_1Layer_definitions = NA
    Opt-Ceilings                       = NA
    Opt-H2KFoundation                  = NA
    Opt-ExposedFloor                   = NA
    Opt-CasementWindows                = NA
    Opt-H2K-PV                         = NA
    Opt-DWHRandSDHW                    = NA 
    Opt-RoofPitch                      = NA
    Opt-DHWSystem                      = NA
    Opt-DWHRSystem                     = NA
    Opt-HVACSystem                     = NA 
    Opt-HRVspec                        = NA, HRV_60, HRV_81

Upgrades_END



