! Definitions file for HTAP-PRM RUN

! Run-Mode: Parameters that affect how htap-prm is configured.
RunParameters_START
  run-mode                           = mesh
  archetype-dir                      = C:/HTAP/testing/h2k-files
  unit-costs-db                      = C:/HTAP/HTAPUnitCosts.json
  options-file                       = C:/HTAP/HTAP-options.json
RunParameters_END


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future.
RunScope_START

  archetypes                        = NRCan-arch4_2100sf_2storey_fullBsmt-v117b23-General.h2k
  locations                         = NA
  rulesets                          = as-found

RunScope_END

! Parameters controlling the design of the building
Upgrades_START


   Opt-ResultHouseCode  = NA

   Opt-ACH         = NA 

   Opt-Windows     = NA , NC-2g-MG-u1.65, NC-3g-MG-u1.08


   Opt-Skylights   = NA
   Opt-DoorWindows = NA
   Opt-Doors       = NA

   Opt-AboveGradeWall = NA

   Opt-FoundationWallExtIns     =  NA
   Opt-FoundationWallIntIns     =  NA
   Opt-FoundationSlabBelowGrade =  NA
   Opt-FoundationSlabOnGrade    =  NA


   Opt-ExposedFloor     = NA

   Opt-Ceilings         = NA
   Opt-AtticCeilings    = NA
   Opt-CathCeilings     = NA
   Opt-FlatCeilings     = NA

   Opt-VentSystem       = NA
   Opt-DHWSystem        = NA
   Opt-Heating-Cooling  = NA, elec-baseboard+AC
   Opt-DWHR             = NA
   Opt-H2K-PV           = NA


   Opt-Baseloads        = NA


Upgrades_END
