! Definitions file for HTAP-PRM RUN 

! Run-Mode: Parameters that affect how htap-prm is configured. 
RunParameters_START
  run-mode                           = parametric
  archetype-dir                      = C:/HTAP/Archetypes
RunParameters_END 


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future. 
RunScope_START

  archetypes                        = BC-Step-MediumSFD.h2k
  locations                         = NA 
  rulesets                          = as-found !, NBC9_36_HRV , R2000_NZE_Pilot_Env
  
  
RunScope_END

! Parameters controlling the design of the building 
Upgrades_START

   Opt-FuelCost         = *
   Opt-DBFiles          = H2KCodeLibFile
   Opt-ResultHouseCode  = *
 
   Opt-Specifications   = *

   Opt-Baseloads        = *   
   Opt-Temperatures     = *
   
   Opt-ACH              = * 
   
   Opt-CasementWindows  = *
   Opt-Skylights        = *
   Opt-DoorWindows      = * 
   Opt-Doors            = *     
  
   Opt-MainWall         = * 
   Opt-GenericWall_1Layer_definitions = * 
   Opt-FloorHeaderIntIns    = *   
  
   Opt-H2KFoundation    = *
  
   Opt-H2KFoundationSlabCrawl = * 
  
   Opt-ExposedFloor     = *
   Opt-ExposedFloor      = *
  
   Opt-FloorAboveCrawl  = * 

   Opt-Ceilings         = *
   Opt-AtticCeilings    = *
   Opt-CathCeilings     = *
   Opt-FlatCeilings     = *
   
   Opt-HRVonly          = *
   Opt-HRVspec          = *
   Opt-DHWSystem        = *
   Opt-HVACSystem       = * 
   Opt-DWHRSystem       = *
   Opt-H2K-PV           = *
    
    
Upgrades_END